services:
  #Основное приложение
  web:
    build: . #Собираем образ из Dockerfile в текущей директории
    ports:
      - "5000:5000" #Пробрасываем порт 5000 на хост
    environment:
      - FLASK_ENV=development
    volumes:
      #Монтируем текущую директорию для горячей перезагрузки кода
      - .:/app
    #Команда для запуска в режиме разработки
    command: python main.py
